[tool.poetry]
name = "rsasignature"
version = "0.1.0"
description = ""
authors = ["lkaubs <221017050@aluno.unb.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
